# -*- coding: utf-8 -*-
"""Selamat Datang di Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

print("hallo word")
input("nama kamu: ")
input("kamu tinggal dimana: ")
input("tanggal lahir kamu: ")
print("")